### PR TITLE
Migrated to python3

### PR DESCRIPTION
**Pull request by prerit2010**

### CODE REVIEW

**Comment by rgaiacs** [comment]
Remove the `*~` files since they are Emacs backup files.

**Comment by rgaiacs** [comment]
Add `excludesfile = /home/raniere/.gitignore_global` to your `~/.gitconfig`.

**Comment by pbanaszkiewicz** [comment]
This seems OK.

**Comment by rgaiacs** [comment]
@prerit2010 Can you squash the commits to really remove the backup files, update this branch and merge it?

**Pull request merged**
