### PR TITLE
Redesign UI

### PR DESCRIPTION
**Pull request by prerit2010**
Added the comparing functionality between 2 packages

### CODE REVIEW

**Comment by prerit2010** [comment]
@pbanaszkiewicz  @rgaiacs  Please have a look at http://installation.software-carpentry.org/view/
Please reload the page to refresh javascript.

**Comment by pbanaszkiewicz** [comment]
@prerit2010 looks good. I'd move "All workshops" (workshop name rectangle with blue background) to the main content (right below "Installation script statistics") and change it to text "Selected workshop: …".

**Comment by rgaiacs** [comment]
@prerit2010 
1. As we talk, drop the "all packages" because the visualisation is poor.
2. "Filter by failed package" is duplicated.
3. What is "all versions"? The version is already mention on the dropdown
4. Use the same layout for the result.

**Comment by prerit2010** [comment]
> As we talk, drop the "all packages" because the visualisation is poor.

@rgaiacs shall I drop both visualizations -- one with versions, and one without versions ?
In that case we can just show collapsible tables sorted by number of failures.

> "Filter by failed package" is duplicated.

As suggested by @pbanaszkiewicz [here](https://github.com/prerit2010/Result-aggregation-server/issues/41#issuecomment-238921076), we now have multiple selections for failed packages, so that we can compare between failed packages. Probably I should change the lables to "Filter by failed package (1)" and "Filter by failed package (2)" On selecting 2 packages, the submit button label changes to "compare".

>  What is "all versions"? The version is already mention on the dropdown

@pbanaszkiewicz  also wanted to see results for a package without being version specific. So suppose I select a pacakage --  pytest (18.4), and also check "all versions", then results will be grouped just by package name -- "pytest".

> Use the same layout for the result.

Currently results are shown on a different end point - `/view/detail/` and thus results it returns are specific to that package only. If we use the same layout we would also need to query everything that is queried by '/view/` to fill the dropdowns in sidebar. Is this the requirement ? Now I feel I should have used something like angularJS from the beginning. :-)

**Comment by rgaiacs** [comment]
> > As we talk, drop the "all packages" because the visualisation is poor.
> 
> shall I drop both visualizations -- one with versions, and one without versions ?
> In that case we can just show collapsible tables sorted by number of failures.

I don't have strong opinion about that yet. We need a bigger database to say something.

> > "Filter by failed package" is duplicated.
> 
> As suggested by @pbanaszkiewicz here, we now have multiple selections for failed packages, so that we can compare between failed packages. Probably I should change the lables to "Filter by failed package (1)" and "Filter by failed package (2)" On selecting 2 packages, the submit button label changes to "compare".

Use "Filter by failed package" and "Also compare with failed package". Or something on this lines.

> > What is "all versions"? The version is already mention on the dropdown
> 
> @pbanaszkiewicz also wanted to see results for a package without being version specific. So suppose I select a pacakage -- pytest (18.4), and also check "all versions", then results will be grouped just by package name -- "pytest".

I suggest to change the logic. The list of packages with version could be very long. Make the user select the package. After select the package, ask if want a specific version.

> > Use the same layout for the result.
> 
> Currently results are shown on a different end point - /view/detail/ and thus results it returns are specific to that package only. If we use the same layout we would also need to query everything that is queried by '/view/` to fill the dropdowns in sidebar. Is this the requirement ?

I will have a look on that later. 

>  Now I feel I should have used something like angularJS from the beginning. :-)

Or React. :-P

**Pull request merged**
